# provider = "anthropic"
# model = "claude-sonnet-4-20250514"
provider = "openai"
model = "gpt-4o-mini"
# provider = "ollama"
# model = "gpt-oss:120b-cloud"
# model = "gpt-oss:20b-cloud"
temperature = 0.0
max_tokens = 16384
workspace = "./workspace"
sandbox_timeout = 60
sandbox_allow_write = true