provider = "anthropic"
# model = "claude-3-5-haiku-20241022"
model = "claude-sonnet-4-20250514"
# provider = "openai"
# model = "gpt-4o-mini"
# provider = "ollama"
# model = "gpt-oss:120b-cloud"
# model = "gpt-oss"
temperature = 0.0
max_tokens = 8192
workspace = "./workspace"
sandbox_timeout = 60
sandbox_allow_write = true
tool_call_output_max_length = 0